SUPABASE_URL = "https://vmrulqvljwpjafwlehja.supabase.co"
SUPABASE_KEY = "sb_publishable_MTd22_IrzD9L2KAYQg7OJg_557La3RF"

EMAIL_FROM = "raragon.carso@gmail.com"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USER = "raragon.carso@gmail.com"
EMAIL_PASSWORD = "svbr czcn nfnt qvzc"